### PR TITLE
Update Delicate Synthesis icons & level 80 formula

### PR DESCRIPTION
**Pull request by ShammyLevva**
Add in delicate synthesis icons for various crafts

### CODE REVIEW

**Comment by doxxx** [comment]
Are you still trying to find some of the icons?

**Comment by ShammyLevva** [comment]
> Are you still trying to find some of the icons?

Not so much trying to find them as need to level crafters to point that icon becomes visible and can be pulled from game :) 

As crafters hit 76 I can do the delicateSynthesis and as they hit 78 I can get the intensiveSynthesis. A work in progress :)

**Comment by ShammyLevva** [comment]
Ok that's added the last of the missing Delicate Synthesis icons.

I've also included the revised level 80 formula which is almost spot on for quality and progress, compared with the current pre-80 formula which is wildly out when you hit 80. This would be a big improvement for beta site to enable more users to test further.

**Comment by doxxx** [comment]
Deployed to beta site.

**Pull request merged**
