### PR TITLE
Add Chinese Localizations

### PR DESCRIPTION
**Pull request by kurax**
I modified db files to add Chinese names to them.

Please make changes to your db generator so the cn field would be keeped while regenerating data.
But I also keep a tool in my fork that can refill cn data when it's missing, but better keep them to avoid more PRs.

### CODE REVIEW

**Comment by kurax** [comment]
Since the Chinese servers have just reached patch 3.5 so there are some recipes have no Chinese names yet, using English names instead.

**Comment by doxxx** [comment]
I'll have a look at improving https://github.com/doxxx/lodestone-recipe-db-scraper to handle this case.

**Comment by kurax** [comment]
FYI Lodestone does not have any chinese data

**Comment by doxxx** [comment]
Yeah, that's what makes this difficult. The scraper tool generates the recipe DB JSON files completely from Lodestone data and I simply overwrite the files in the ffxiv-craft-opt-web project with the output from that.

I'm contemplating making the scraper load the names from the existing JSON files and use that as a fallback for names that it can't find on the Lodestone. The tricky part will be correlating recipes since I don't currently store any kind of unique identifier that is independent of the human readable names.

**Comment by kurax** [comment]
I can provide a JSON file for the scraper with "en name": "cn name" pairs of all items data if it helps

**Comment by doxxx** [comment]
That would help, yes.

I've noticed that the Lodestone has recipe IDs in the URL that it also uses for generating links to recipes in the Eorzea DB comments. For example Armorer's Bronze Ingot URL is "http://na.finalfantasyxiv.com/lodestone/playguide/db/recipe/c394d841f12/" and the ID is the last segment: "c394d841f12".

Are you able to correlate the Chinese names with those recipe IDs? That would allow the scraper to match the Chinese name to a recipe even when the English name has changed (they adjust the spelling of recipe names sometimes).

**Comment by kurax** [comment]
The Lodestone's id is not "real" id the game uses so it's very hard to match them with Chinese names.
But since I'll update this JSON file no matter na or cn server patches, so it may not be a problem.

**Comment by doxxx** [comment]
Ok. Let's try the en->cn name JSON file.

**Comment by kurax** [comment]
I'll create a PR with the JSON to the scraper later, but I'm not good at python, so I'll leave it to you to make use of it :grinning:

**Comment by doxxx** [comment]
Sure, no problem.

**Comment by doxxx** [comment]
Put the PR on https://github.com/doxxx/lodestone-recipe-db-scraper.

**Pull request merged**
