### PR TITLE
Reflect was stacking up too many initial inner quiets

### PR DESCRIPTION
**Pull request by AricStewart**
Should be 3 total

### CODE REVIEW

**Comment by doxxx** [comment]
From my reading of the action on Garland Tools, it's supposed to set the stack of Inner Quiet to 3.

**Comment by AricStewart** [comment]
Agreed however I was getting 5 instead of 3 without this patch. Why I am not sure. So maybe there is a bug somewhere else

**Comment by AricStewart** [comment]
Ok new version pushed I did a bit more digging. 
1. Because Reflect also increases quality we where getting an extra stack from it in UpdateEffectCounters
1. the countUps stack starts at 0; so that means a value of 2 is a count of 3. 

New patch pushed.

**Comment by doxxx** [comment]
Thanks, that makes sense!

**Comment by doxxx** [comment]
Deployed to ffxiv-beta.lokyst.net.

**Pull request merged**
