### PR TITLE
undoing size change for sequence and making solution visible if there have been changes

### PR DESCRIPTION
**Pull request by noshlag**

### CODE REVIEW

**Comment by noshlag** [comment]
It's not intuitive to have the initial guess and the solver result be different sizes.  It makes it hard to tell at a glance that no change has occurred:

image

If we leave them the same size, it's much cleaner:
image


The other change is to have the Solver Result show up while the solver is running, if an improvement has been found so the user has an indication that there is a result.  This is useful if you are running a heavy simulation load trying to optimize a macro for high level crafts.  

image

**Comment by doxxx** [comment]
The result being greyed out (as well as the grey "no change" text) is the indicator that the result hasn't changed. But I do agree that the different size makes it more difficult to see. Especially if there are in fact changes, the different size makes it harder to spot where they differ.

**Comment by doxxx** [comment]
FYI, you should use rebase to leave out commits that should already be included. Using the revert means that merging this PR actually reverted your change from #351. I've fixed it in master.

**Comment by doxxx** [comment]
Deployed to https://ffxiv-beta.lokyst.net

**Comment by noshlag** [comment]
Thank you for fixing the rebase issue.

**Pull request merged**
