### PR TITLE
Add new python script to get recipes from xivdb 

### PR DESCRIPTION
**Pull request by Ley21**
View commits for detail informations

### CODE REVIEW

**Comment by Ley21** [comment]
Hello,
because i had some time I fixed my bugs and finished my python script. It will get all information from xivdb and create for each Class an json file, like you use it. I think this could help you to update the recipes fast.

**Comment by doxxx** [comment]
I think you still need to compensate for the difficulty_factor, durability_factor and quality_factor fields from the xivdb data. Compare a recipe for which these fields are != 100 to the recipe info on the Lodestone.

**Comment by doxxx** [comment]
For example, recipe id 2783 "Crystal Glass".

**Comment by doxxx** [comment]
Lodestone link: http://na.finalfantasyxiv.com/lodestone/playguide/db/recipe/6c2a99fac17/

**Pull request closed without merging**
