### PR TITLE
Update ffxivcraftmodel.js

### PR DESCRIPTION
**Pull request by Igor-Yavych**
Fixed Ingenuity and Ingenuity II for 60 lvl 2, 3 and 4*

### CODE REVIEW

**Comment by doxxx** [comment]
How large a dataset have you tested these new values on?

**Comment by Igor-Yavych** [comment]
Few recipes for each star level with 2 different values of craftsmanship. So far it seems to be accurate. Unlike how it is right now.

**Comment by doxxx** [comment]
Fair enough. Since we can't test it in game ourselves, and the change seems reasonable, I'll have to trust you. :)

**Comment by doxxx** [comment]
Change is deployed to beta site.

**Comment by Igor-Yavych** [comment]
Great. Thanks. There is also a problem with inaccurate CS 2 (unbuffed) where it's off by 2, but I haven't found the correct value.

**Comment by doxxx** [comment]
That one's going to be trickier. :)

**Comment by Igor-Yavych** [comment]
Haha, indeed. Also, still don't see changes at http://ffxiv-beta.lokyst.net/#/simulator

**Comment by doxxx** [comment]
I've verified that the file has been updated on the webhost, so you may need to force a refresh in your browser.

**Comment by Igor-Yavych** [comment]
It seems like leveldiff penalty is not capped at -6. For 4* it's capped at -8 and for 3* at -7. I got numbers right, but there is mismatch for either regular synthesis (100%) or rapid synthesis (250%).  I think I'm getting  close.

**Pull request merged**
