### PR TITLE
Features/only guaranteed actions by level

### PR DESCRIPTION
**Pull request by noshlag**
Ignore the comments about the Math.Floor.  That's just because my master branch on my fork has that change, but it's not been merged into the upstream master yet.

The actual changes:
- Remove Standard Synthesis and add Basic Synthesis 2 instead.
- Update images accordingly.
- Add button to filter out non-guaranteed actions (actions with less than 100% success chance)
- On ByLevel and Guaranteed filtering, remove the non-upgraded versions of Basic Synthesis and Rapid Synthesis

### CODE REVIEW

**Comment by noshlag** [comment]
This is what the new organization looks like: 

image

**Comment by noshlag** [comment]
And filtered to guaranteed looks like this:

image

**Comment by doxxx** [comment]
Please rebase onto master to avoid reverting existing changes as happened with #352.

**Comment by doxxx** [comment]
Hmm, that's still not quite right. That's a merge, not a rebase. I can do it, if you don't mind.

**Comment by doxxx** [comment]
Ah, I think I see what went wrong. Rebase require a force-push, you probably allowed your git client to pull merge instead. All sorted. :)

**Comment by doxxx** [comment]
When loading saved sequences from the user profile in local storage, do you think 'standardSynth' actions should be converted to 'basicSynth2'?

**Comment by noshlag** [comment]
Ah, good call! I should add that backwards compatability.

**Comment by doxxx** [comment]
Thanks! To save you some searching, that's in `ProfileService.prototype.load` in `profile.js`.

**Comment by noshlag** [comment]
Added the back compat.  I think I implemented it in the cleanest place.

**Comment by doxxx** [comment]
Yup, that looks good!

**Comment by doxxx** [comment]
Deployed to beta site.

**Pull request merged**
