### PR TITLE
update 5.0

### PR DESCRIPTION
**Pull request by SaltFish-X**
I modified three places

1. update calculateBaseProgressIncrease & calculateBaseQualityIncrease use new formula
2. add control limit；maxControl = originControl + 3000
3. update ingenuity reference teamCrafter

Best Wish

### CODE REVIEW

**Comment by doxxx** [comment]
Thank you so much!

**Comment by doxxx** [comment]
@SaltFish-X: I've made a few minor changes to your updates here: 14b793ea071826c73b4de71d5ef59ff7330a0514

It's mostly formatting and naming changes to suit my style preferences. I also rewrote the level difference factor lookup function (`getLevelDif`) to simplify it and make it harder for bugs to creep in later.

Please let me know if you disagree with any of these changes by commenting on that commit.

**Comment by SaltFish-X** [comment]
Your code is better！
it inspired me a lot。

**Comment by SaltFish-X** [comment]
```
    // Since game version 5.0, effects increasing control are capped at crafter's original control + 3000
    control = Math.max(control, s.synth.crafter.control + 3000);
```

Here is wrong
But You have changed in [6d797d](https://github.com/doxxx/ffxiv-craft-opt-web/commit/6d797d53d91a1b129affd53503cd55990bf7688b)

**Pull request merged**
