### PR TITLE
Adjust Innovation skill for 5.2

### PR DESCRIPTION
**Pull request by agocke**
Innovation was changed to no longer affect progress, but have a larger effect
on quality.

### CODE REVIEW

**Comment by doxxx** [comment]
Thanks!

**Comment by agocke** [comment]
Thanks! This is an awesome project, really enjoying using it and reading the source.

**Comment by doxxx** [comment]
> reading the source.

Oh dear... ;)

**Comment by doxxx** [comment]
Also, deployed to beta site.

**Pull request merged**
