### PR TITLE
Arabic json file added

### PR DESCRIPTION
**Pull request by AhmadAymanA99**
added an arabic translation.
not complete.

### CODE REVIEW

**Comment by doxxx** [comment]
Thanks! I’m currently on vacation so I’ll merge this when I get back in about 2 weeks time.

**Comment by AhmadAymanA99** [comment]
ar.json ===> completed
I hope a good luck for you.

**Comment by doxxx** [comment]
Thanks!

**Comment by doxxx** [comment]
Deployed to ffxiv-beta.lokyst.net.

**Pull request merged**
