### PR TITLE
Patch 5.11

### PR DESCRIPTION
**Pull request by EpicElric**
Added new recipes from 5.1 and 5.11. ID numbers and translations are missing. This is mainly to help doxxx with for when he returns.

### CODE REVIEW

**Comment by tanpro260196** [comment]
The facet crafting and gathering gear from 5.1 seems to be missing?

**Comment by EpicElric** [comment]
I didn't realize they were missing. I will take a look when I get home tonight and see if I can add them.

**Comment by kongspark** [comment]
The database files is created by the scraper. I will fix this.

**Comment by EpicElric** [comment]
> The database files is created by the scraper. I will fix this.

I dont't know how to use the scraper, for now I just added the recipes by hand and they will work for people waiting on the official update.

**Comment by doxxx** [comment]
Thanks, @EpicElric, I've merged the PR from @kongspark.

**Pull request closed without merging**
